# Generated by Django 2.2.1 on 2019-05-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
